Use selenium driver by default
Capybara expects the browser object to be a selenium driver, not
an appium driver.

The following code is used to start a pry session:

> pry

require 'appium_capybara'

Capybara.register_driver(:appium) do |app|
    opts = Appium.load_appium_txt file: File.join(Dir.pwd, 'appium.txt')
    Appium::Capybara::Driver.new app, opts
end

Capybara.default_driver = :appium

capy_driver = Capybara.current_session.driver
capy_driver.browser

Notice that selenium methods will fail.

> capy_driver.go_back
NoMethodError: undefined method `navigate' for #<Appium::Driver:0x007fafda14d570

These methods exist on the selenium driver and the browser is set to the appium driver.

The changes in this Pull Request fix the default so the upstream capybara commands work.

> capy_driver.go_back
post /back